spring:
  datasource:
    url: jdbc:mysql://localhost:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: retail
    password: retail
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# Caching (in-memory by default). To use Redis, add spring-boot-starter-data-redis and set host/port.
